### ISSUE TITLE
feat: add websocket support

### ISSUE THREAD

**Issue by ajndkr** [ajndkr/fastapi-async-langchain#11]
This project is currently limited to streaming responses. For building applications like chatbots, users might require a websockets-based solution.

The idea is already implemented in https://github.com/hwchase17/chat-langchain. We can integrate it here as well.

**Comment by ajndkr** [comment]
thanks! would be nice to have all fastapi tooling in one place :)

**Comment by pors** [comment]
Cool! BTW this might break (it did for me) with langchain vs 0.0.154 or higher. See https://github.com/hwchase17/langchain/pull/3256#issuecomment-1531831107

**Comment by ajndkr** [comment]
will check this out!

**Comment by pors** [comment]
It is fixed in langchain 0.0.156. They move fast :)

Just make sure to import like `from langchain.callbacks.manager import AsyncCallbackManager`

**Comment by ajndkr** [comment]
there's already PR open for this :D #19

**Comment by pors** [comment]
Someone else is moving fast as well 😀
