### ISSUE TITLE
Unexpected ASGI message 'http.response.body' sent, after response already completed.

### ISSUE THREAD

**Issue by Tooflex** [ajndkr/fastapi-async-langchain#17]
I'm getting this error message randomly when I launch the conversation_chain example : 
- Unexpected ASGI message 'http.response.body' sent, after response already completed.

**Comment by Tooflex** [comment]
Nevermind, in fact it's just that the web socket closes at some point. The client just need to re-establish the connection

**Comment by ajndkr** [comment]
cool. closing issue.
