### ISSUE TITLE
Stablelm instead of openai? 

### ISSUE THREAD

**Issue by ngmisl** [ajndkr/fastapi-async-langchain#2]
Would it be possible to add open and free openai alternatives via langchain?

Thinking about https://huggingface.co/spaces/stabilityai/stablelm-tuned-alpha-chat

Would be very cool and open up some nice use cases. In our case we'd add it to a game, can hardly ask gamers to add a paid openai key (or use my own) at this point ✌️

**Comment by ajndkr** [comment]
Hi! based on the langchain docs, I think should be possible. You can find the relevant docs here: https://python.langchain.com/en/latest/modules/models/llms/integrations/huggingface_pipelines.html

I highly recommend asking the same on the langchain repo: https://github.com/hwchase17/langchain/issues as this repo is mainly towards adding FastAPI streaming support for LLM chains built with langchain.
