### ISSUE TITLE
ConversationalRetrievalChain

### ISSUE THREAD

**Issue by audvin** [ajndkr/fastapi-async-langchain#29]
Would this work together with ConversationalRetrievalChain?

E.g.
```
qa = ConversationalRetrievalChain(
    retriever=vectorstore.as_retriever(),
    combine_docs_chain=doc_chain,
    question_generator=question_generator,
    return_source_documents=False,
    get_chat_history=get_chat_history,
)
```

Ref: https://langchain-fanyi.readthedocs.io/en/latest/modules/chains/index_examples/chat_vector_db.html?highlight=ConversationalRetrievalChain#conversationalretrievalchain-with-streaming-to-stdout

**Comment by ajndkr** [comment]
Hi! We already have a PR open towards this! #16. 

It’s still in progress.

**Comment by rogalvil** [comment]
An apology, I've been a bit busy but I'll get back to it

**Comment by ajndkr** [comment]
No rush!

**Comment by audvin** [comment]
That's awesome to hear! 🙏

**Comment by ajndkr** [comment]
@audvin streaming response support for ConversationalRetrievalChain has been added in `0.4.4`. It should be available via pip soon!

let us know if it works!

**Comment by tejeshbhalla** [comment]
@ajndkr  if i want to call the streaming handler i get the crux one thing i wanna know if i am not mainting history on the frontend side is there a way to get the whole response after its done streaming to commit it back to the db as history ?
