### ISSUE TITLE
Issue with second message

### ISSUE THREAD

**Issue by rogalvil** [ajndkr/fastapi-async-langchain#3]
I was testing it and the first message worked correctly but if I make a second request it shows the following error.

![Captura de pantalla 2023-04-21 a la(s) 17 55 23](https://user-images.githubusercontent.com/695923/233750271-13ac7192-b7f1-4bb1-aa6c-ce729e8b293c.png)

**Comment by haixinglps** [comment]
我这里也遇到这问题。我用的python3.8环境。3.9不清楚

**Comment by ajndkr** [comment]
Hi @rogalvil, I was able to reproduce the issue on my end. Likely a bug in `AsyncFastApiStreamingCallback`. Looking into it.

**Comment by ajndkr** [comment]
Hi @haixinglps, this package supports python 3.9+ at the moment. You can use a conda virtual environment for this.

**Comment by ajndkr** [comment]
@rogalvil I've pushed a fix and made a new release. Please re-install the package: `pip install fastapi-async-langchain==0.1.1` and try again. Let me know if you face any issues.

**Comment by haixinglps** [comment]
> Hi @haixinglps, this package supports python 3.9+ at the moment. You can use a conda virtual environment for this.

ok

**Comment by rogalvil** [comment]
@ajndkr Thank you very much, now it works for me.
