### ISSUE TITLE
Langchain dependency errors when installing with other libraries

### ISSUE THREAD

**Issue by jpdus** [ajndkr/fastapi-async-langchain#37]
The langchain version in pyproject.toml is fixed via a caret requirement (`langchain = "^0.0.164"`) .

As langchain is updated almost daily, this makes fastapi-async-langchain basically unusable with other langchain-dependent modules, e.g.:

```Because jpllm (0.0.4) depends on langchain (^0.0.166)
 and fastapi-async-langchain (0.5.2) depends on langchain (>=0.0.164,<0.0.165), jpllm (0.0.4)  is incompatible with fastapi-async-langchain (0.5.2). 
`` ``

It would be great to change the langchain requirement to e.g. ">0.0.164"  or "~0.0.164"  to make the use more flexible.

**Comment by ajndkr** [comment]
@jpdus pushed a fix in `0.5.3` version. should be available soon!
